// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7a1o-r5M_3uwmdBPQp0tA0KOttvgOrtI',
    appId: '1:266430320334:web:b89a520aeddd4892694a9f',
    messagingSenderId: '266430320334',
    projectId: 'drop4life-9f1b0',
    authDomain: 'drop4life-9f1b0.firebaseapp.com',
    storageBucket: 'drop4life-9f1b0.firebasestorage.app',
    measurementId: 'G-0HXT3HWB1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_-goyXQIGgQZ5O5gVvYCZyE8hvRC2ZA',
    appId: '1:266430320334:android:79a5b9eaaea5fe3d694a9f',
    messagingSenderId: '266430320334',
    projectId: 'drop4life-9f1b0',
    storageBucket: 'drop4life-9f1b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRkjgiWaITLh4PH5JjEyhwxZUl1z1eCRQ',
    appId: '1:266430320334:ios:937f9be58700c287694a9f',
    messagingSenderId: '266430320334',
    projectId: 'drop4life-9f1b0',
    storageBucket: 'drop4life-9f1b0.firebasestorage.app',
    iosBundleId: 'com.example.drop4life',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRkjgiWaITLh4PH5JjEyhwxZUl1z1eCRQ',
    appId: '1:266430320334:ios:937f9be58700c287694a9f',
    messagingSenderId: '266430320334',
    projectId: 'drop4life-9f1b0',
    storageBucket: 'drop4life-9f1b0.firebasestorage.app',
    iosBundleId: 'com.example.drop4life',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7a1o-r5M_3uwmdBPQp0tA0KOttvgOrtI',
    appId: '1:266430320334:web:672f81b012ec716d694a9f',
    messagingSenderId: '266430320334',
    projectId: 'drop4life-9f1b0',
    authDomain: 'drop4life-9f1b0.firebaseapp.com',
    storageBucket: 'drop4life-9f1b0.firebasestorage.app',
    measurementId: 'G-E6V7256JDK',
  );
}
