from fastapi import FastAPI
from backend.database import Base, engine
from typing import Optional 
from backend.routers import donors, blood_requests, hospitals, users
from backend.firebase import initialize_firebase

initialize_firebase()

app = FastAPI(
    title="Drop4Life",
    description="API for connecting blood donors with those in need",
    version="1.0.0",
)


Base.metadata.create_all(bind=engine)

app.include_router(donors.router)
app.include_router(blood_requests.router)
app.include_router(hospitals.router) 
app.include_router(users.router)       

@app.get("/")
def read_root():
    return {
        "status": "running",
        "message": "Welcome to Drop4Life!",
        "version": "1.0.0",
    }


# # ─────────────────────────────────────────
# # DONORS
# # Rule: /donors/search/{x} MUST come before /donors/{id}
# # because FastAPI matches top-to-bottom
# # ─────────────────────────────────────────

# @app.get("/donors/search/{blood_group}")
# def search_donors_by_blood_group(blood_group: str):
#     """Search donors by blood group. Example: GET /donors/search/O+"""
#     mock_donors = [
#         {"id": 1, "name": "Arjun Mehta",  "blood_group": blood_group, "city": "Mumbai"},
#         {"id": 2, "name": "Priya Sharma", "blood_group": blood_group, "city": "Pune"},
#     ]
#     return {
#         "blood_group": blood_group,
#         "total_found": len(mock_donors),
#         "donors": mock_donors,
#     }


# @app.get("/donors/{donor_id}")
# def get_donor_by_id(donor_id: int):
#     """Get a single donor by ID. Example: GET /donors/1"""
#     return {
#         "id": donor_id,
#         "name": "Arjun Mehta",
#         "blood_group": "O+",
#         "age": 25,
#         "city": "Mumbai",
#         "phone": "9876543210",
#     }


# @app.post("/donors/register")
# def register_donor(donor_data: dict):
#     """
#     Register a new donor.

#     Expected body:
#     {
#         "name": "Rahul Verma",
#         "blood_group": "O+",
#         "city": "Mumbai",
#         "phone": "9876543210",
#         "age": 28
#     }
#     """
#     return {
#         "message": "Donor registered successfully",
#         "donor": {
#             "id": 999,       # will be auto-generated by DB in Phase 3
#             **donor_data,
#         },
#     }


# # ─────────────────────────────────────────
# # BLOOD REQUESTS
# # ─────────────────────────────────────────

# # Optional[str] = None  means the parameter is optional.
# # If ?city=Mumbai is in the URL, city = "Mumbai"
# # If not provided, city = None → return all requests

# @app.get("/blood-requests")
# def get_blood_requests(city: Optional[str] = None):
#     """
#     Get all active blood requests.
#     Optional filter: GET /blood-requests?city=Mumbai
#     """
#     all_requests = [
#         {
#             "id": 1,
#             "blood_group_needed": "A+",
#             "hospital": "Lilavati Hospital",
#             "city": "Mumbai",
#             "urgency": "critical",
#         },
#         {
#             "id": 2,
#             "blood_group_needed": "O-",
#             "hospital": "AIIMS",
#             "city": "Delhi",
#             "urgency": "urgent",
#         },
#         {
#             "id": 3,
#             "blood_group_needed": "B+",
#             "hospital": "Ruby Hall Clinic",
#             "city": "Pune",
#             "urgency": "normal",
#         },
#     ]

#     # Apply city filter if provided
#     if city:
#         filtered = [r for r in all_requests if r["city"].lower() == city.lower()]
#         return {
#             "filter_applied": {"city": city},
#             "total_found": len(filtered),
#             "requests": filtered,
#         }

#     return {
#         "total_found": len(all_requests),
#         "requests": all_requests,
#     }


# @app.post("/blood-requests/create")
# def create_blood_request(request_data: dict):
#     """
#     Create a new blood request.

#     Expected body:
#     {
#         "blood_group_needed": "A+",
#         "hospital": "Lilavati Hospital",
#         "city": "Mumbai",
#         "urgency": "critical"
#     }
#     """
#     # Validate urgency value — basic check before Pydantic arrives in Phase 2
#     valid_urgency = ["critical", "urgent", "normal"]
#     urgency = request_data.get("urgency", "").lower()

#     if urgency not in valid_urgency:
#         return {
#             "error": f"Invalid urgency. Must be one of: {valid_urgency}"
#         }

#     return {
#         "message": "Blood request created successfully",
#         "request": {
#             "id": 888,
#             **request_data,
#         },
#     }