"""initial clean schema

Revision ID: 16221a798d97
Revises: 
Create Date: 2026-03-27 18:47:07.569267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16221a798d97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('blood_group', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='bloodgroupenum'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('availability', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'BUSY', name='availabilityenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_donors_id'), 'donors', ['id'], unique=False)
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('blood_inventory', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_hospitals_city'), 'hospitals', ['city'], unique=False)
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_table('blood_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_group_needed', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='bloodgroupenum'), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('units_needed', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.Enum('CRITICAL', 'URGENT', 'NORMAL', name='urgencyenum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FULFILLED', 'CANCELLED', name='statusenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_requests_id'), 'blood_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blood_requests_id'), table_name='blood_requests')
    op.drop_table('blood_requests')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_city'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_donors_id'), table_name='donors')
    op.drop_table('donors')
    # ### end Alembic commands ###
