"""add_location_to_donor

Revision ID: 20ac9e3cf35b
Revises: 94f12806ee75
Create Date: 2026-04-12 11:27:13.174108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ac9e3cf35b'
down_revision: Union[str, Sequence[str], None] = '94f12806ee75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('donors', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donors', 'longitude')
    op.drop_column('donors', 'latitude')
    # ### end Alembic commands ###
