"""add_location_to_hospital

Revision ID: 8ab52cb6ab59
Revises: 20ac9e3cf35b
Create Date: 2026-04-12 12:01:49.361649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ab52cb6ab59'
down_revision: Union[str, Sequence[str], None] = '20ac9e3cf35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('hospitals', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'longitude')
    op.drop_column('hospitals', 'latitude')
    # ### end Alembic commands ###
