"""add_cooldown_fields_to_donor

Revision ID: 94f12806ee75
Revises: 7139c3433c61
Create Date: 2026-04-12 10:41:13.225928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f12806ee75'
down_revision: Union[str, Sequence[str], None] = '7139c3433c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('last_donation_date', sa.Date(), nullable=True))
    op.add_column('donors', sa.Column('cooldown_until', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donors', 'cooldown_until')
    op.drop_column('donors', 'last_donation_date')
    # ### end Alembic commands ###
